import { Drug, DrugSolution } from "@/types";

export const DRUGS: Drug[] = [
  // ===== FREE: VASOPRESSORES =====
  {
    id: "norepinefrina",
    name: "Norepinefrina",
    category: "vasopressor",
    ampPresentation: "8mg/4mL",
    isFree: true,
    doseUnit: "mcg/kg/min",
    usesWeight: true,
    maxFlowRate: 200,
    solutions: [
      {
        id: "nora-sp",
        drugName: "Norepinefrina",
        shortName: "NORA SP",
        dilutionType: "SP",
        ampoules: 1,
        ampouleDrugContent_mg: 8,
        ampouleVolume_mL: 4,
        diluent: "SG5",
        diluentVolume_mL: 246,
        totalVolume_mL: 250,
        totalDrug_mg: 8,
        concentration_mcg_per_mL: 32,
        label: "01 AMP + 246mL SG5%",
      },
      {
        id: "nora-cc",
        drugName: "Norepinefrina",
        shortName: "NORA CC",
        dilutionType: "CC",
        ampoules: 2,
        ampouleDrugContent_mg: 8,
        ampouleVolume_mL: 4,
        diluent: "SG5",
        diluentVolume_mL: 242,
        totalVolume_mL: 250,
        totalDrug_mg: 16,
        concentration_mcg_per_mL: 64,
        label: "02 AMP + 242mL SG5%",
      },
      {
        id: "nora-2xcc",
        drugName: "Norepinefrina",
        shortName: "NORA 2xCC",
        dilutionType: "2xCC",
        ampoules: 4,
        ampouleDrugContent_mg: 8,
        ampouleVolume_mL: 4,
        diluent: "SG5",
        diluentVolume_mL: 234,
        totalVolume_mL: 250,
        totalDrug_mg: 32,
        concentration_mcg_per_mL: 128,
        label: "04 AMP + 234mL SG5%",
      },
    ],
    doseRanges: [
      { min: 0, max: 0.1, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 0.1, max: 0.3, label: "DOSE MODERADA", color: "#facc15" },
      { min: 0.3, max: 0.5, label: "DOSE ALTA", color: "#fb923c" },
      { min: 0.5, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Catecolamina com potente acao vasoconstritora (alfa-1) e efeito inotropico positivo (beta-1).",
      "Droga de primeira escolha no choque septico (Surviving Sepsis 2021).",
      "Dose habitual: 0.1 a 0.5 mcg/kg/min.",
      "Doses acima de 0.5 mcg/kg/min indicam choque refratario — considerar associacao de vasopressina.",
      "Administrar preferencialmente em acesso venoso central.",
    ],
  },
  {
    id: "vasopressina",
    name: "Vasopressina",
    category: "vasopressor",
    ampPresentation: "20UI/1mL",
    isFree: true,
    doseUnit: "U/min",
    usesWeight: false,
    maxFlowRate: 15,
    solutions: [
      {
        id: "vaso-sp",
        drugName: "Vasopressina",
        shortName: "VASO SP",
        dilutionType: "SP",
        ampoules: 1,
        ampouleDrugContent_mg: 20,
        ampouleVolume_mL: 1,
        diluent: "SF09",
        diluentVolume_mL: 99,
        totalVolume_mL: 100,
        totalDrug_mg: 20,
        concentration_mcg_per_mL: 0.2,
        label: "01 AMP + 99mL SF0,9%",
      },
      {
        id: "vaso-cc",
        drugName: "Vasopressina",
        shortName: "VASO CC",
        dilutionType: "CC",
        ampoules: 2,
        ampouleDrugContent_mg: 20,
        ampouleVolume_mL: 1,
        diluent: "SF09",
        diluentVolume_mL: 98,
        totalVolume_mL: 100,
        totalDrug_mg: 40,
        concentration_mcg_per_mL: 0.4,
        label: "02 AMP + 98mL SF0,9%",
      },
    ],
    doseRanges: [
      { min: 0, max: 0.01, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 0.01, max: 0.03, label: "DOSE MODERADA", color: "#facc15" },
      { min: 0.03, max: 0.04, label: "DOSE ALTA", color: "#fb923c" },
      { min: 0.04, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Hormonio antidiuretico com acao vasoconstritora (receptores V1).",
      "Segunda linha no choque septico, associada a noradrenalina (Surviving Sepsis 2021).",
      "Dose fixa habitual: 0.03 a 0.04 U/min.",
      "Nao titular por peso — dose fixa.",
      "Doses acima de 0.04 U/min associadas a isquemia mesenterica e digital.",
    ],
  },
  {
    id: "dobutamina",
    name: "Dobutamina",
    category: "vasopressor",
    ampPresentation: "250mg/20mL",
    isFree: true,
    doseUnit: "mcg/kg/min",
    usesWeight: true,
    maxFlowRate: 100,
    solutions: [
      {
        id: "dobu-sp",
        drugName: "Dobutamina",
        shortName: "DOBUTAMINA SP",
        dilutionType: "SP",
        ampoules: 1,
        ampouleDrugContent_mg: 250,
        ampouleVolume_mL: 20,
        diluent: "SG5",
        diluentVolume_mL: 230,
        totalVolume_mL: 250,
        totalDrug_mg: 250,
        concentration_mcg_per_mL: 1000,
        label: "01 AMP + 230mL SG5%",
      },
      {
        id: "dobu-cc",
        drugName: "Dobutamina",
        shortName: "DOBUTAMINA CC",
        dilutionType: "CC",
        ampoules: 2,
        ampouleDrugContent_mg: 250,
        ampouleVolume_mL: 20,
        diluent: "SG5",
        diluentVolume_mL: 210,
        totalVolume_mL: 250,
        totalDrug_mg: 500,
        concentration_mcg_per_mL: 2000,
        label: "02 AMP + 210mL SG5%",
      },
      {
        id: "dobu-2xcc",
        drugName: "Dobutamina",
        shortName: "DOBUTAMINA 2xCC",
        dilutionType: "2xCC",
        ampoules: 4,
        ampouleDrugContent_mg: 250,
        ampouleVolume_mL: 20,
        diluent: "SG5",
        diluentVolume_mL: 170,
        totalVolume_mL: 250,
        totalDrug_mg: 1000,
        concentration_mcg_per_mL: 4000,
        label: "04 AMP + 170mL SG5%",
      },
    ],
    doseRanges: [
      { min: 0, max: 5, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 5, max: 10, label: "DOSE MODERADA", color: "#facc15" },
      { min: 10, max: 15, label: "DOSE ALTA", color: "#fb923c" },
      { min: 15, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Catecolamina sintetica com acao inotropica positiva predominante (beta-1).",
      "Droga de escolha no choque cardiogenico e insuficiencia cardiaca aguda.",
      "Dose habitual: 2.5 a 20 mcg/kg/min.",
      "Efeito cronotropico positivo — monitorar taquicardia.",
      "Pode causar hipotensao por vasodilatacao (beta-2) em doses baixas.",
    ],
  },
  // ===== PREMIUM: VASOPRESSORES =====
  {
    id: "dopamina",
    name: "Dopamina",
    category: "vasopressor",
    ampPresentation: "50mg/10mL",
    isFree: false,
    doseUnit: "mcg/kg/min",
    usesWeight: true,
    maxFlowRate: 100,
    solutions: [
      {
        id: "dopa-sp",
        drugName: "Dopamina",
        shortName: "DOPAMINA SP",
        dilutionType: "SP",
        ampoules: 5,
        ampouleDrugContent_mg: 50,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 200,
        totalVolume_mL: 250,
        totalDrug_mg: 250,
        concentration_mcg_per_mL: 1000,
        label: "05 AMP + 200mL SG5%",
      },
      {
        id: "dopa-cc",
        drugName: "Dopamina",
        shortName: "DOPAMINA CC",
        dilutionType: "CC",
        ampoules: 10,
        ampouleDrugContent_mg: 50,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 150,
        totalVolume_mL: 250,
        totalDrug_mg: 500,
        concentration_mcg_per_mL: 2000,
        label: "10 AMP + 150mL SG5%",
      },
      {
        id: "dopa-2xcc",
        drugName: "Dopamina",
        shortName: "DOPAMINA 2xCC",
        dilutionType: "2xCC",
        ampoules: 10,
        ampouleDrugContent_mg: 50,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 50,
        totalVolume_mL: 150,
        totalDrug_mg: 500,
        concentration_mcg_per_mL: 3333.33,
        label: "10 AMP + 50mL SG5%",
      },
    ],
    doseRanges: [
      { min: 0, max: 3, label: "DOSE DOPAMINERGICA", color: "#4ade80" },
      { min: 3, max: 10, label: "DOSE BETA", color: "#facc15" },
      { min: 10, max: 20, label: "DOSE ALFA", color: "#fb923c" },
      { min: 20, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Catecolamina endogena com efeitos dose-dependentes: dopaminergico, beta e alfa.",
      "Dose < 3 mcg/kg/min: efeito dopaminergico (renal — controverso).",
      "Dose 3-10 mcg/kg/min: efeito beta-1 (inotropico e cronotropico).",
      "Dose > 10 mcg/kg/min: efeito alfa-1 (vasoconstritor).",
      "Maior incidencia de arritmias comparada a norepinefrina (SOAP II Trial).",
    ],
  },
  {
    id: "epinefrina",
    name: "Epinefrina",
    category: "vasopressor",
    ampPresentation: "1mg/1mL",
    isFree: false,
    doseUnit: "mcg/kg/min",
    usesWeight: true,
    maxFlowRate: 100,
    solutions: [
      {
        id: "epi-sp",
        drugName: "Epinefrina",
        shortName: "EPINEFRINA SP",
        dilutionType: "SP",
        ampoules: 1,
        ampouleDrugContent_mg: 1,
        ampouleVolume_mL: 1,
        diluent: "SG5",
        diluentVolume_mL: 249,
        totalVolume_mL: 250,
        totalDrug_mg: 1,
        concentration_mcg_per_mL: 4,
        label: "01 AMP + 249mL SG5%",
      },
      {
        id: "epi-cc",
        drugName: "Epinefrina",
        shortName: "EPINEFRINA CC",
        dilutionType: "CC",
        ampoules: 2,
        ampouleDrugContent_mg: 1,
        ampouleVolume_mL: 1,
        diluent: "SG5",
        diluentVolume_mL: 248,
        totalVolume_mL: 250,
        totalDrug_mg: 2,
        concentration_mcg_per_mL: 8,
        label: "02 AMP + 248mL SG5%",
      },
      {
        id: "epi-2xcc",
        drugName: "Epinefrina",
        shortName: "EPINEFRINA 2xCC",
        dilutionType: "2xCC",
        ampoules: 4,
        ampouleDrugContent_mg: 1,
        ampouleVolume_mL: 1,
        diluent: "SG5",
        diluentVolume_mL: 246,
        totalVolume_mL: 250,
        totalDrug_mg: 4,
        concentration_mcg_per_mL: 16,
        label: "04 AMP + 246mL SG5%",
      },
    ],
    doseRanges: [
      { min: 0, max: 0.05, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 0.05, max: 0.1, label: "DOSE MODERADA", color: "#facc15" },
      { min: 0.1, max: 0.3, label: "DOSE ALTA", color: "#fb923c" },
      { min: 0.3, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Catecolamina endogena com acao alfa e beta-adrenergica.",
      "Indicada no choque anafilatico e como segunda linha no choque septico.",
      "Dose habitual em infusao: 0.01 a 0.3 mcg/kg/min.",
      "Potente efeito cronotropico — risco de taquiarritmias.",
      "Pode ser usada como alternativa a dobutamina no choque cardiogenico.",
    ],
  },
  // ===== PREMIUM: SEDACAO =====
  {
    id: "fentanila",
    name: "Fentanila",
    category: "analgesic",
    ampPresentation: "500mcg/10mL",
    isFree: false,
    doseUnit: "mcg/kg/h",
    usesWeight: true,
    maxFlowRate: 50,
    solutions: [
      {
        id: "fenta-sp",
        drugName: "Fentanila",
        shortName: "FENTANILA SP",
        dilutionType: "SP",
        ampoules: 5,
        ampouleDrugContent_mg: 0.5,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 200,
        totalVolume_mL: 250,
        totalDrug_mg: 2.5,
        concentration_mcg_per_mL: 10,
        label: "05 AMP + 200mL SG5%",
      },
      {
        id: "fenta-cc",
        drugName: "Fentanila",
        shortName: "FENTANILA CC",
        dilutionType: "CC",
        ampoules: 10,
        ampouleDrugContent_mg: 0.5,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 150,
        totalVolume_mL: 250,
        totalDrug_mg: 5,
        concentration_mcg_per_mL: 20,
        label: "10 AMP + 150mL SG5%",
      },
      {
        id: "fenta-2xcc",
        drugName: "Fentanila",
        shortName: "FENTANILA 2xCC",
        dilutionType: "2xCC",
        ampoules: 20,
        ampouleDrugContent_mg: 0.5,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 50,
        totalVolume_mL: 250,
        totalDrug_mg: 10,
        concentration_mcg_per_mL: 40,
        label: "20 AMP + 50mL SG5%",
      },
    ],
    doseRanges: [
      { min: 0, max: 1, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 1, max: 2, label: "DOSE MODERADA", color: "#facc15" },
      { min: 2, max: 4, label: "DOSE ALTA", color: "#fb923c" },
      { min: 4, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Opioide sintetico potente com rapido inicio de acao.",
      "Analgesia e sedacao em pacientes sob ventilacao mecanica (PADIS 2018).",
      "Dose habitual em infusao continua: 0.5 a 3 mcg/kg/h.",
      "Risco de rigidez toracica em bolus rapido.",
      "Monitorar depressao respiratoria e hipotensao.",
    ],
  },
  {
    id: "midazolam",
    name: "Midazolam",
    category: "sedation",
    ampPresentation: "50mg/10mL",
    isFree: false,
    doseUnit: "mg/kg/h",
    usesWeight: true,
    maxFlowRate: 50,
    solutions: [
      {
        id: "mida-sp",
        drugName: "Midazolam",
        shortName: "MIDAZOLAM SP",
        dilutionType: "SP",
        ampoules: 5,
        ampouleDrugContent_mg: 50,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 200,
        totalVolume_mL: 250,
        totalDrug_mg: 250,
        concentration_mcg_per_mL: 1000,
        label: "05 AMP + 200mL SG5%",
      },
      {
        id: "mida-cc",
        drugName: "Midazolam",
        shortName: "MIDAZOLAM CC",
        dilutionType: "CC",
        ampoules: 10,
        ampouleDrugContent_mg: 50,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 200,
        totalVolume_mL: 300,
        totalDrug_mg: 500,
        concentration_mcg_per_mL: 1666.67,
        label: "10 AMP + 200mL SG5%",
      },
      {
        id: "mida-2xcc",
        drugName: "Midazolam",
        shortName: "MIDAZOLAM 2xCC",
        dilutionType: "2xCC",
        ampoules: 20,
        ampouleDrugContent_mg: 50,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 200,
        totalVolume_mL: 400,
        totalDrug_mg: 1000,
        concentration_mcg_per_mL: 2500,
        label: "20 AMP + 200mL SG5%",
      },
    ],
    doseRanges: [
      { min: 0, max: 0.05, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 0.05, max: 0.1, label: "DOSE MODERADA", color: "#facc15" },
      { min: 0.1, max: 0.2, label: "DOSE ALTA", color: "#fb923c" },
      { min: 0.2, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Benzodiazepınico de acao curta com propriedades sedativas, ansioliticas e amnesticas.",
      "Sedacao em UTI para pacientes sob ventilacao mecanica.",
      "Dose habitual: 0.02 a 0.1 mg/kg/h.",
      "Acumulo em infusoes prolongadas — preferir propofol ou dexmedetomidina (PADIS 2018).",
      "Monitorar nivel de sedacao (RASS).",
    ],
  },
  {
    id: "propofol",
    name: "Propofol",
    category: "sedation",
    ampPresentation: "200mg/20mL (1%)",
    isFree: false,
    doseUnit: "mg/kg/h",
    usesWeight: true,
    maxFlowRate: 80,
    solutions: [
      {
        id: "prop-200-20",
        drugName: "Propofol",
        shortName: "PROPOFOL 1% 20mL",
        dilutionType: "SP",
        ampoules: 1,
        ampouleDrugContent_mg: 200,
        ampouleVolume_mL: 20,
        diluent: "SG5",
        diluentVolume_mL: 0,
        totalVolume_mL: 20,
        totalDrug_mg: 200,
        concentration_mcg_per_mL: 10000,
        label: "200mg / 20mL (1%)",
        specialNote: "Solucao pura — nao diluir.",
      },
      {
        id: "prop-500-50",
        drugName: "Propofol",
        shortName: "PROPOFOL 1% 50mL",
        dilutionType: "CC",
        ampoules: 1,
        ampouleDrugContent_mg: 500,
        ampouleVolume_mL: 50,
        diluent: "SG5",
        diluentVolume_mL: 0,
        totalVolume_mL: 50,
        totalDrug_mg: 500,
        concentration_mcg_per_mL: 10000,
        label: "500mg / 50mL (1%)",
        specialNote: "Solucao pura — nao diluir. Trocar seringa a cada 12h.",
      },
    ],
    doseRanges: [
      { min: 0, max: 2, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 2, max: 4, label: "DOSE MODERADA", color: "#facc15" },
      { min: 4, max: 5, label: "DOSE ALTA", color: "#fb923c" },
      { min: 5, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Hipnotico de acao ultracurta com rapida recuperacao.",
      "Sedacao em UTI — preferido sobre benzodiazepinicos (PADIS 2018).",
      "Dose habitual: 1 a 4 mg/kg/h.",
      "Atencao a sindrome da infusao do propofol (PRIS) em doses > 5 mg/kg/h por > 48h.",
      "Contem lipideos — considerar no aporte calorico. Trocar seringa a cada 12h.",
    ],
  },
  {
    id: "cetamina",
    name: "Cetamina",
    category: "sedation",
    ampPresentation: "500mg/10mL",
    isFree: false,
    doseUnit: "mg/kg/h",
    usesWeight: true,
    maxFlowRate: 50,
    solutions: [
      {
        id: "ceta-sp",
        drugName: "Cetamina",
        shortName: "CETAMINA SP",
        dilutionType: "SP",
        ampoules: 1,
        ampouleDrugContent_mg: 500,
        ampouleVolume_mL: 10,
        diluent: "SF09",
        diluentVolume_mL: 250,
        totalVolume_mL: 260,
        totalDrug_mg: 500,
        concentration_mcg_per_mL: 1923.08,
        label: "01 AMP + 250mL SF0,9%",
      },
      {
        id: "ceta-cc",
        drugName: "Cetamina",
        shortName: "CETAMINA CC",
        dilutionType: "CC",
        ampoules: 2,
        ampouleDrugContent_mg: 500,
        ampouleVolume_mL: 10,
        diluent: "SF09",
        diluentVolume_mL: 210,
        totalVolume_mL: 230,
        totalDrug_mg: 1000,
        concentration_mcg_per_mL: 4347.83,
        label: "02 AMP + 210mL SF0,9%",
      },
    ],
    doseRanges: [
      { min: 0, max: 0.5, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 0.5, max: 1, label: "DOSE MODERADA", color: "#facc15" },
      { min: 1, max: 2, label: "DOSE ALTA", color: "#fb923c" },
      { min: 2, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Anestesico dissociativo com propriedades analgesicas e broncodilatadoras.",
      "Util como adjuvante na sedacao e analgesia em UTI.",
      "Dose habitual em infusao: 0.1 a 1 mg/kg/h.",
      "Efeito poupador de opioides — reduz necessidade de fentanil.",
      "Pode causar sialorreia, alucinacoes e elevacao da PIC em doses altas.",
    ],
  },
  {
    id: "dexmedetomidina",
    name: "Dexmedetomidina",
    category: "sedation",
    ampPresentation: "200mcg/2mL",
    isFree: false,
    doseUnit: "mcg/kg/h",
    usesWeight: true,
    maxFlowRate: 50,
    solutions: [
      {
        id: "dexm-sp",
        drugName: "Dexmedetomidina",
        shortName: "DEXMED SP",
        dilutionType: "SP",
        ampoules: 2,
        ampouleDrugContent_mg: 0.2,
        ampouleVolume_mL: 2,
        diluent: "SF09",
        diluentVolume_mL: 96,
        totalVolume_mL: 100,
        totalDrug_mg: 0.4,
        concentration_mcg_per_mL: 4,
        label: "02 AMP + 96mL SF0,9%",
        specialNote: "NAO UTILIZAR SG 5%.",
      },
    ],
    doseRanges: [
      { min: 0, max: 0.4, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 0.4, max: 0.7, label: "DOSE MODERADA", color: "#facc15" },
      { min: 0.7, max: 1.0, label: "DOSE ALTA", color: "#fb923c" },
      { min: 1.0, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Agonista alfa-2 central com propriedades sedativas e analgesicas.",
      "Sedacao cooperativa — paciente desperta ao estimulo (PADIS 2018).",
      "Dose habitual: 0.2 a 0.7 mcg/kg/h (max 1.4 mcg/kg/h).",
      "Menor risco de delirium comparado a benzodiazepinicos.",
      "Pode causar bradicardia e hipotensao. NAO diluir em SG 5%.",
    ],
  },
  // ===== PREMIUM: ANALGESICOS =====
  {
    id: "morfina",
    name: "Morfina",
    category: "analgesic",
    ampPresentation: "10mg/1mL",
    isFree: false,
    doseUnit: "mg/h",
    usesWeight: false,
    maxFlowRate: 20,
    solutions: [
      {
        id: "morf-sp",
        drugName: "Morfina",
        shortName: "MORFINA SP",
        dilutionType: "SP",
        ampoules: 10,
        ampouleDrugContent_mg: 10,
        ampouleVolume_mL: 1,
        diluent: "SF09",
        diluentVolume_mL: 90,
        totalVolume_mL: 100,
        totalDrug_mg: 100,
        concentration_mcg_per_mL: 1000,
        label: "10 AMP + 90mL SF0,9%",
      },
    ],
    doseRanges: [
      { min: 0, max: 2, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 2, max: 5, label: "DOSE MODERADA", color: "#facc15" },
      { min: 5, max: 10, label: "DOSE ALTA", color: "#fb923c" },
      { min: 10, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Opioide natural com potente acao analgesica.",
      "Dose habitual em infusao continua: 1 a 5 mg/h.",
      "Metabolito ativo (M6G) acumula em insuficiencia renal.",
      "Pode causar liberacao de histamina — evitar em broncoespasmo.",
      "Monitorar sedacao, depressao respiratoria e motilidade intestinal.",
    ],
  },
  // ===== PREMIUM: BLOQUEADORES NEUROMUSCULARES =====
  {
    id: "rocuronio",
    name: "Rocuronio",
    category: "neuromuscular_blocker",
    ampPresentation: "5mg/5mL",
    isFree: false,
    doseUnit: "mcg/kg/min",
    usesWeight: true,
    maxFlowRate: 30,
    solutions: [
      {
        id: "rocu-sp",
        drugName: "Rocuronio",
        shortName: "ROCURONIO SP",
        dilutionType: "SP",
        ampoules: 5,
        ampouleDrugContent_mg: 5,
        ampouleVolume_mL: 5,
        diluent: "SG5",
        diluentVolume_mL: 225,
        totalVolume_mL: 250,
        totalDrug_mg: 25,
        concentration_mcg_per_mL: 100,
        label: "05 AMP + 225mL SG5%",
      },
    ],
    doseRanges: [
      { min: 0, max: 5, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 5, max: 10, label: "DOSE MODERADA", color: "#facc15" },
      { min: 10, max: 15, label: "DOSE ALTA", color: "#fb923c" },
      { min: 15, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Bloqueador neuromuscular aminoesteroide de acao intermediaria.",
      "Indicado para paralisia neuromuscular em pacientes sob ventilacao mecanica.",
      "Dose habitual em infusao: 5 a 12 mcg/kg/min.",
      "SEMPRE associar sedacao e analgesia adequadas — paciente paralizado sente dor.",
      "Monitorar com TOF (Train of Four) a cada 4-6h. Objetivo: TOF 1-2/4.",
    ],
  },
  {
    id: "atracurio",
    name: "Atracurio",
    category: "neuromuscular_blocker",
    ampPresentation: "25mg/5mL",
    isFree: false,
    doseUnit: "mcg/kg/min",
    usesWeight: true,
    maxFlowRate: 30,
    solutions: [
      {
        id: "atra-sp",
        drugName: "Atracurio",
        shortName: "ATRACURIO SP",
        dilutionType: "SP",
        ampoules: 5,
        ampouleDrugContent_mg: 25,
        ampouleVolume_mL: 5,
        diluent: "SG5",
        diluentVolume_mL: 225,
        totalVolume_mL: 250,
        totalDrug_mg: 125,
        concentration_mcg_per_mL: 500,
        label: "05 AMP + 225mL SG5%",
      },
      {
        id: "atra-cc",
        drugName: "Atracurio",
        shortName: "ATRACURIO CC",
        dilutionType: "CC",
        ampoules: 5,
        ampouleDrugContent_mg: 25,
        ampouleVolume_mL: 5,
        diluent: "SG5",
        diluentVolume_mL: 200,
        totalVolume_mL: 225,
        totalDrug_mg: 125,
        concentration_mcg_per_mL: 555.56,
        label: "05 AMP + 200mL SG5%",
      },
    ],
    doseRanges: [
      { min: 0, max: 5, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 5, max: 10, label: "DOSE MODERADA", color: "#facc15" },
      { min: 10, max: 15, label: "DOSE ALTA", color: "#fb923c" },
      { min: 15, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Bloqueador neuromuscular benzilisoquinolinico de acao intermediaria.",
      "Metabolismo por via de Hofmann — seguro em insuficiencia renal e hepatica.",
      "Dose habitual em infusao: 4 a 12 mcg/kg/min.",
      "SEMPRE associar sedacao e analgesia adequadas.",
      "Pode causar liberacao de histamina — cuidado em pacientes asmaticos.",
    ],
  },
  {
    id: "cisatracurio",
    name: "Cisatracurio",
    category: "neuromuscular_blocker",
    ampPresentation: "20mg/10mL",
    isFree: false,
    doseUnit: "mcg/kg/min",
    usesWeight: true,
    maxFlowRate: 30,
    solutions: [
      {
        id: "cisa-sp",
        drugName: "Cisatracurio",
        shortName: "CISATRACURIO SP",
        dilutionType: "SP",
        ampoules: 5,
        ampouleDrugContent_mg: 20,
        ampouleVolume_mL: 10,
        diluent: "SF09",
        diluentVolume_mL: 150,
        totalVolume_mL: 200,
        totalDrug_mg: 100,
        concentration_mcg_per_mL: 500,
        label: "05 AMP + 150mL SF0,9%",
      },
    ],
    doseRanges: [
      { min: 0, max: 1, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 1, max: 2, label: "DOSE MODERADA", color: "#facc15" },
      { min: 2, max: 5, label: "DOSE ALTA", color: "#fb923c" },
      { min: 5, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Isomero cis-cis do atracurio, 3x mais potente.",
      "Metabolismo por via de Hofmann — ideal para insuficiencia hepatica/renal.",
      "Dose habitual em infusao: 1 a 3 mcg/kg/min.",
      "Menor liberacao de histamina que atracurio.",
      "Monitorar com TOF. Droga de escolha para BNM prolongado em UTI (ACURASYS Trial).",
    ],
  },
  // ===== PREMIUM: VASODILATADORES =====
  {
    id: "nitroglicerina",
    name: "Nitroglicerina",
    category: "vasodilator",
    ampPresentation: "50mg/10mL",
    isFree: false,
    doseUnit: "mcg/min",
    usesWeight: false,
    maxFlowRate: 100,
    solutions: [
      {
        id: "ntg-sp",
        drugName: "Nitroglicerina",
        shortName: "NTG SP",
        dilutionType: "SP",
        ampoules: 1,
        ampouleDrugContent_mg: 50,
        ampouleVolume_mL: 10,
        diluent: "SG5",
        diluentVolume_mL: 240,
        totalVolume_mL: 250,
        totalDrug_mg: 50,
        concentration_mcg_per_mL: 200,
        label: "01 AMP + 240mL SG5%",
        specialNote: "CC e 2xCC: usar equipo de bomba free.",
      },
    ],
    doseRanges: [
      { min: 0, max: 20, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 20, max: 100, label: "DOSE MODERADA", color: "#facc15" },
      { min: 100, max: 200, label: "DOSE ALTA", color: "#fb923c" },
      { min: 200, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Vasodilatador predominantemente venoso (baixas doses) e arterial (altas doses).",
      "Indicada em sindrome coronariana aguda e emergencia hipertensiva.",
      "Dose habitual: 5 a 200 mcg/min.",
      "Taquifilaxia apos 24-48h de uso continuo.",
      "Usar equipo especial (nao adsorve PVC) em concentracoes elevadas.",
    ],
  },
  {
    id: "nitroprussiato",
    name: "Nitroprussiato de Sodio",
    category: "vasodilator",
    ampPresentation: "25mg/2mL",
    isFree: false,
    doseUnit: "mcg/kg/min",
    usesWeight: true,
    maxFlowRate: 100,
    solutions: [
      {
        id: "nps-sp",
        drugName: "Nitroprussiato",
        shortName: "NPS SP",
        dilutionType: "SP",
        ampoules: 1,
        ampouleDrugContent_mg: 25,
        ampouleVolume_mL: 2,
        diluent: "SG5",
        diluentVolume_mL: 250,
        totalVolume_mL: 252,
        totalDrug_mg: 25,
        concentration_mcg_per_mL: 99.21,
        label: "01 AMP + 250mL SG5%",
        specialNote: "Proteger da luz — fotossensivel.",
      },
      {
        id: "nps-cc",
        drugName: "Nitroprussiato",
        shortName: "NPS CC",
        dilutionType: "CC",
        ampoules: 2,
        ampouleDrugContent_mg: 25,
        ampouleVolume_mL: 2,
        diluent: "SG5",
        diluentVolume_mL: 245,
        totalVolume_mL: 249,
        totalDrug_mg: 50,
        concentration_mcg_per_mL: 200.80,
        label: "02 AMP + 245mL SG5%",
        specialNote: "Proteger da luz — fotossensivel.",
      },
    ],
    doseRanges: [
      { min: 0, max: 1, label: "DOSE BAIXA", color: "#4ade80" },
      { min: 1, max: 3, label: "DOSE MODERADA", color: "#facc15" },
      { min: 3, max: 5, label: "DOSE ALTA", color: "#fb923c" },
      { min: 5, max: Infinity, label: "DOSE MUITO ALTA", color: "#ef4444" },
    ],
    clinicalNotes: [
      "Vasodilatador arterial e venoso direto (oxido nitrico).",
      "Droga de escolha na emergencia hipertensiva com encefalopatia.",
      "Dose habitual: 0.3 a 5 mcg/kg/min (max 10 mcg/kg/min).",
      "Risco de intoxicacao por cianeto em uso prolongado (> 48h) ou doses > 2 mcg/kg/min.",
      "PROTEGER DA LUZ — usar equipo fotoprotetor.",
    ],
  },
];

// ===== HELPER FUNCTIONS =====

export function getAvailableDrugs(isPremium: boolean): Drug[] {
  return isPremium ? DRUGS : DRUGS.filter((d) => d.isFree);
}

export function getFreeDrugs(): Drug[] {
  return DRUGS.filter((d) => d.isFree);
}

export function getPremiumDrugs(): Drug[] {
  return DRUGS.filter((d) => !d.isFree);
}

export function getDrugById(id: string): Drug {
  return DRUGS.find((d) => d.id === id) ?? DRUGS[0];
}

export function getSolutionById(id: string): DrugSolution {
  for (const drug of DRUGS) {
    const sol = drug.solutions.find((s) => s.id === id);
    if (sol) return sol;
  }
  return DRUGS[0].solutions[0];
}

export function getDrugBySolutionId(solutionId: string): Drug {
  return (
    DRUGS.find((d) => d.solutions.some((s) => s.id === solutionId)) ?? DRUGS[0]
  );
}

export function getDrugsByCategory(category: string): Drug[] {
  return DRUGS.filter((d) => d.category === category);
}
